<?php
/**
 * Generated by PHPUnit on 2012-09-15 at 23:57:29.
 */
class Bill
{
    /**
     * @todo Implement getStandardHtml().
     */
    public function getStandardHtml()
    {
        // Remove the following line when you implement this method.
        throw new RuntimeException('Not yet implemented.');
    }
}
?>
